Реализована функция сравнения строк.
js-tasks-ru/js-20201030_irina-sidd pull request #2
Opened 2020-11-04 21:30 UTC by IrinkaSidd

2020-11-04 22:39 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-05 09:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
- should return new object with one passed field
- should return new object with a few passed field
- should return an empty object if passed fields does not found
```
```diff
omit
- should return a new object without passed field
- should return a new object without few passed fields
- should return initial object if passed fields doesn't found
```

2020-11-05 11:38 UTC, IrinkaSidd commented
Решены задачи к уроку "Основы JS. Примитивные типы данных".

2020-11-05 11:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-06 14:33 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return result.reverse();
попробуйте избавиться от `reverse` - это лишняя операция. Было бы неплохо сортировать массив сразу в нужном порядке

2020-11-06 14:34 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +      delete obj[key];
не стоит удалять свойства из объекта, так как объект это ссылочный тип, данное удаление может привести к негативным последствиям - подробнее обсудим на занятии

2020-11-06 14:38 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-06 16:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-06 19:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-06 20:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-09 12:12 UTC, dosandk approved these changes
good 👍

2020-11-09 12:13 UTC, merged